name: SleepyMood
favicon: null
layout_spectrum: 0.44103
typography_spectrum: 0
title: Sleepy Mood
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0d0f10'
    - '#c3d6de'
    - '#a1b7c0'
    - '#3e4c50'
  brandStrength: 0.5
  lightness: 0.003327557584270835
  saturation: 0.24823271040804684
  rhythmicContrast: 0.34973358432762325
purpose: []
