name: SleepyMood
favicon: null
layout_spectrum: 0.4479801601264626
typography_spectrum: 0.36970943259075284
title: Sleepy Mood
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.0797986479010433
  lightness: 0.003327557584270835
  saturation: 0.24823271040804684
  rhythmicContrast: 0.34973358432762325
purpose: []
